name: Deploy to surge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm install --global surge && ./ surge --domain cooperative-poison.surge.sh --token a163ceda0ff44eedd3b38fafcd63dece